image: archlinux
packages:
  - nodejs
  - npm
sources:
  - https://git.sr.ht/~djlooop/contacts2js
tasks:
  - setup: |
      cd contacts2js
      npm install
  - test: |
      cd contacts2js
      npm test


