env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - plugin:fp/recommended
  - eslint:recommended
plugins:
  - fp
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
